//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagerRemakeApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmtpServer
    {
        public int Id { get; set; }
        public string SmtpServerIp { get; set; }
        public string SmtpServerPort { get; set; }
        public string SmtpLogin { get; set; }
        public string SmtpPassword { get; set; }
    }
}
