//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagerRemakeApp.Data
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class TaskFile
    {
        public int Id { get; set; }
        public int TaskId { get; set; }
        public byte[] AttachedFile { get; set; }
        public string AttachedFileName { get; set; }
    
        public virtual Task Task { get; set; }

        public string AttachedFileExt
        {
            get
            {
                char[] sep = { '.' };
                if (AttachedFileName.Contains('.'))
                    return AttachedFileName.Split(sep, StringSplitOptions.RemoveEmptyEntries).Last();
                else
                    return "FILE";
            }
        }
    }
}
